on:
  workflow_call:
    inputs:
      registry:
        type: string

jobs:
  write:
    if: inputs.registry == 'ghcr'
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to GHCR
  print:
    if: inputs.registry != 'ghcr'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to Docker Hub
