name: Trigger
on:
  workflow_dispatch:
    inputs:
      registry:
        type: string
        default: dockerhub

jobs:
  ghcr:
    if: inputs.registry == 'ghcr'
    permissions:
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      registry: ${{ inputs.registry }}

  dockerhub:
    if: inputs.registry != 'ghcr'
    uses: ./.github/workflows/deploy.yml
    with:
      registry: ${{ inputs.registry }}
